### ISSUE TITLE
SQL检测失败但仍然可以提交？

### ISSUE THREAD

**Issue by dikang123** [jly8866/archer#14]
![image](https://cloud.githubusercontent.com/assets/16694535/25733353/cb828046-318a-11e7-8ca8-b389fca8f8a1.png)
SQL审核之后，显示为失败的状态，但是“sql提交按钮”仍然可以点击并提交

**Comment by jetbinliu** [comment]
你那不是失败，这是warning，不是error。

**Comment by jly8866** [comment]
这些是warning而已，inception返回的errlevel只是认为为1，审核是否成功与是否能提交无关

**Comment by dikang123** [comment]
ok。
