### ISSUE TITLE
选择要上线的集群能否加集群排序功能，按照名字排序不然会很乱

### ISSUE THREAD

**Issue by himura-kenshin** [jly8866/archer#15]

**Comment by zzucjl** [comment]
可以使用python的有序字典实现排序
方法1：
from django.utils.datastructures import SortedDict 
d2 = SortedDict() 
d2['b'] = 1 
d2['a'] = 2 
d2['c'] = 3 
方法2：
from collections import defaultdict
dd = defaultdict(lambda: 'N/A')
dd['key1'] = 'abc'
 dd['key1'] # key1存在
'abc'
dd['key2'] # key2不存在，返回默认值
'N/A'
方法3：
 from collections import OrderedDict
d = dict([('a', 1), ('b', 2), ('c', 3)])
d # dict的Key是无序的
{'a': 1, 'c': 3, 'b': 2}
 od = OrderedDict([('a', 1), ('b', 2), ('c', 3)])
 od # OrderedDict的Key是有序的
OrderedDict([('a', 1), ('b', 2), ('c', 3)])

**Comment by jly8866** [comment]
@himura-kenshin   已经由作者 @johnliu2008  修复，请知晓。
