### ISSUE TITLE
docker需求

### ISSUE THREAD

**Issue by dikang123** [jly8866/archer#3]
有没有考虑做成docker镜像，这样安装配置会比较方便？

**Comment by jly8866** [comment]
可以考虑啊，image提交到哪个registry比较合适？

**Comment by yebinjei** [comment]
可以提交到官方的Docker hub

**Comment by jly8866** [comment]
@dikang123 @himura-kenshin docker镜像已经制作好，详见https://github.com/jly8866/archer  的#已经制作好的docker镜像#部分，感谢支持!

**Comment by dikang123** [comment]
thx
