### ISSUE TITLE
慢日志明细显示不准确问题

### ISSUE THREAD

**Issue by jdj199222** [jly8866/archer#94]
慢日志统计里含有50条并且总时间10s多一点但是明细里只有11条,并且每条执行时间看起来花费更多,11条总时间大概10s多一点. 少了39条明细

慢日志获取频率 每10分钟一次

![image](https://user-images.githubusercontent.com/40590418/45332657-7959ea80-b5a4-11e8-85e9-40ea2519891b.png)
![image](https://user-images.githubusercontent.com/40590418/45332667-8aa2f700-b5a4-11e8-8ddf-48b4e88c71a6.png)

**Comment by hhyo** [comment]
@jdj199222 明细也不是具体到每一条，是指每次分析区间（10分钟）的执行情况，这里少了显示一列执行次数，可以 [查看调整后的展示](https://github.com/hhyo/archer) ，后续会合并至主项目。
